### ISSUE TITLE
CPU 100%

### ISSUE THREAD

**Issue by Ruba85** [ringcentral/hubspot-embeddable-ringcentral-phone#300] opened 2022-07-26 12:54 UTC
Hello.
Our manager begin to complain that their laptop overload during work with hubspot.
I made some test on clean laptop where no one work with hubspot and ringcentral before.
First only hubspot all works fine.
But only i install your widget i receive a lot of events in console when open contact page.
And this page overload cpu of laptop
![image](https://user-images.githubusercontent.com/58745486/181009027-9aedb629-41b3-47e2-bf1b-1a8f65d3fb8d.png)
![image](https://user-images.githubusercontent.com/58745486/181010231-5b7882e1-4cde-48f2-a12f-c4ce62b0377b.png)

**Comment by Ruba85** [comment] 2022-07-26 13:41
![image](https://user-images.githubusercontent.com/58745486/181019973-b1ed9aea-102c-4c12-9f82-9a51ac6589f5.png)
![image](https://user-images.githubusercontent.com/58745486/181020177-06ff1e24-1dad-4a38-8be4-0299b7690314.png)
![image](https://user-images.githubusercontent.com/58745486/181020373-fdc41cb4-7a7d-402b-901d-bb6c2663909e.png)

**Comment by Ruba85** [comment] 2022-07-26 13:42
![image](https://user-images.githubusercontent.com/58745486/181020504-a2cbf626-da4e-4fc3-8127-ad14c66db96f.png)

**Comment by embbnux** [comment] 2022-07-28 05:19
Hi @Ruba85 Can you right click the Console logs and select "Save as" save log as file. And send the log file to https://developers.ringcentral.com/support/create-case , then share case tile  here.

**Comment by embbnux** [comment] 2022-07-29 03:53
Can you help to provide detail steps that you reproduce this issue. I try to reproduce, but I can't get same issue and logs.

For last log screenshot, it is caused by Auto log calls enabled. Can you try to disable it in the extension to see if it can help to avoid this issue.

And it seems that "hasAnalyticDiag" log is not from this extension. Can you help to click "content.js" link at the log to get full URI to check if it is from the extension.

**Comment by Ruba85** [comment] 2022-08-01 18:13
We don't see this problem any more. We checked on different laptops where this problem was notice. And all works fine now

**Comment by embbnux** [comment] 2022-08-02 02:04
Thanks for confirming. I am going to close this issue. Feel free to reopen if you get it again.

**Closed as completed by embbnux** 2022-08-02 02:04 UTC
