### ISSUE TITLE
Contact Issue

### ISSUE THREAD

**Issue by jmlugares** [ringcentral/hubspot-embeddable-ringcentral-phone#156] opened 2019-08-15 22:47 UTC
Hello Team,

I have an ongoing issue with Hub spot after installing 1.3.8. I am unable to sync the softphone app and getting an error "No Related Contacts" even after clicking the refresh button. Please see screen shot as reference

![image](https://user-images.githubusercontent.com/52936394/63131827-a0f5d600-bff1-11e9-974d-469c7ee62008.png)

**Comment by zxdong262** [comment] 2019-08-16 00:54
Please check this: https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/137

Since it shows number, not a contact name, it means it is not synced to widgets contacts list, you may check the contacts-hubspot filter. You can open browser console to check if there are errors after click reload contacts, if you have many contacts, you may take a while to finish sync, make sure it finished, you can confirmed by search from contact list.

You may read this to open background page console: https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/154

If you still have problems, we may arrange a meeting to find out why.

**Comment by zxdong262** [comment] 2019-12-12 05:40
Close it now, feel free to submit another one.

**Closed by zxdong262** 2019-12-12 05:40 UTC
